### ISSUE TITLE
Delayed audio playback on Linux

### ISSUE THREAD

**Issue by scholar-mage** [avivbeeri/dome#10]
Sound effects seem to have about a ~1s delay on my Linux machine, even after extensive tweaking of PulseAudio settings. That delay is much less noticeable on Windows, probably around ~0.25s or less. Further investigation is needed to determine if this happens on other boxes or platforms.

**Comment by avivbeeri** [comment]
Because of the extensive work to the AudioEngine in #17 and #18, I'm not sure if this is still an issue, so it will need more testing.

**Comment by Sandvich** [comment]
Just to chime in, I don't see this on OpenSuse using the latest builds :)
