### ISSUE TITLE
Allow DOME to create folders

### ISSUE THREAD

**Issue by avivbeeri** [avivbeeri/dome#102]
Proposed API:
`FileSystem.createDirectory(path)` would behave like `mkdir -p` on unix systems, where any missing folders are created on the way.

It should Fiber.abort if the directory couldn't be created for some reason.

**Comment by siddhantrao23** [comment]
I'd love to work on this. The `tinydir` library doesn't support mkdir afaik, how do you suppose this functionality can be replicated, using `mkdir()` recursively or another library like [https://github.com/stephenmathieson/mkdirp.c]()?

**Comment by avivbeeri** [comment]
Since the `tinydir`author recommends that `mkdirp` library (https://github.com/cxong/tinydir/issues/11), we can at least give it a go. I'd rather not maintain a recursive implementation of my own if we don't have to, and this already appears to precisely solve our issues, and even handles the cross-platform concerns we would worry about.
