### ISSUE TITLE
[idea] Provide Dome built in class

### ISSUE THREAD

**Issue by clsource** [avivbeeri/dome#108]
For simplifying code,
a global class could be created to access the most common dome modules in a single unit.
without need to import it explicitly.

This can be added using the same logic for detecting built in modules such as `System`.

Current
```js
import "graphics" for Canvas, Color
import "input" for Keyboard
import "dome" for Window
```

Could be simplified as

```js
Dome.canvas
Dome.color
Dome.input
Dome.window
```

Example Implementation

```js
// MARK: - Dome
class Input {
  static keyboard {Keyboard}
  static mouse {Mouse}
  static gamepad {GamePad}
}

class Audio {
  static engine {AudioEngine}
  static channel {AudioChannel}
  static state {AudioState}
}

class Graphics {
  static canvas {Canvas}
  static color {Color}
  static image {ImageData}
  static point {Point}
  static drawable {Drawable}
}

class Dome {
  static window {Window}
  static process {Process}
  static canvas {Graphics.canvas}
  static color {Graphics.color}  
  static audio {Audio}
  static io {FileSystem}
  static random {Random}
  static graphics {Graphics}
  static input {Input}
  static font {Font}
  static version {Version}
  static math {Math}
  static vector {Vector}
}
```

**Comment by clsource** [comment]
To document why this was closed:

@avivbeeri 
> There's some resource cost to loading all the built in modules up front like that. Input and Audio have some resources they only hold on to when they are imported.
> You can use a global class in your own projects if you wish, but I don't think it's appropriate for the core

**Comment by avivbeeri** [comment]
I also felt it didn't provide any syntactic benefits beyond "less imports", at the cost of requiring the user to prefix everything with `dome.`. which is an additional layer of verbosity. for minimal gain.
