### ISSUE TITLE
Best practice for VCS

### ISSUE THREAD

**Issue by Sandvich** [avivbeeri/dome#31]
There should be an established best practice for working with VCS.

Initially I just checked the executable in, but this doesn't work if you're working on multiple platforms. My second approach was to use a symlink, but as it turns out the loading is done relative to the binary path, not relative to the symlink.

My other main thoughts are:
- A start script that detects the platform and launches the correct binary (only useful for mac/linux)
- Adding the dome repo as a submodule (still has the symlink problem, and you now have to make every time you want to build on a new computer)

**Comment by avivbeeri** [comment]
Thanks to #32, we gain some flexibility. You should be able to symlink DOME, or install it somewhere on your execution PATH and run it. Alternatively, just drop the executable into whichever folder you want your game code in and run it from there.
