### ISSUE TITLE
AudioEngine names must be lowercase

### ISSUE THREAD

**Issue by Sandvich** [avivbeeri/dome#36]
The _name_ assigned to a file in AudioEngine has to be only lowercase characters (I didn't try any special characters). At least, this is what it looks like to me :p 

This isn't a _problem_, per se, but it should be documented.

**Comment by avivbeeri** [comment]
There's no reason for this to be the case: The audio "names" are stored in a wren Map, which are case sensitive, so it should work for any case, so long as the string is identical.

I also can't reproduce this, so it might be a bug in Wren.
