### ISSUE TITLE
Canvas.line seems to reach incorrect endpoint

### ISSUE THREAD

**Issue by chrislewisdev** [avivbeeri/dome#52]
Hi, I'm testing out a few small DOME features to familiarise myself ahead of DOME jam :)

I'm trying out some alternate screen sizes (in this case 400x240px) and noticed that drawing a line from one corner of the screen to another doesn't seem to behave as expected.

With this example code I get the following result:
```
import "dome" for Window
import "graphics" for Canvas, Color

class Game {
    static init() {
      Window.resize(400, 240)
      Canvas.resize(400, 240)
    }
    static update() {}
    static draw(dt) {
      Canvas.rect(0, 0, 400, 240, Color.white)
      Canvas.line(0, 0, 400, 240, Color.blue)
      Canvas.print("%(Canvas.width)", 1, 1, Color.red)
      Canvas.print("%(Canvas.height)", 1, 10, Color.red)
    }
}
```

![image](https://user-images.githubusercontent.com/395415/76212129-e3b41f80-625b-11ea-8815-06472b29ec32.png)

Notice how the `rect()` function with width/height matching the screen correctly draws a border from one corner of the screen to another, however the line drawn with `line()` does not touch the corner of the screen as I'm expecting.

I'm not sure if this is related to the specific screen size I've chosen or just the `line` function in general, but in any case this doesn't match how I'd expect it to behave.

Thanks!

**Comment by avivbeeri** [comment]
Oh wow, I've not seen that before! I can confirm this is a bug, and I will try to get it fixed up before DOMEjam. 

I'm hoping to push out DOME 1.1.0 before then, including a mixture of performance and bug fixes, as well as a couple new features.

**Comment by avivbeeri** [comment]
Turns out my implementation of Bresenham's Line Algorithm was wrong, resulting in deformed lines. Two-line fix!

**Comment by chrislewisdev** [comment]
Awesome, thanks @avivbeeri!
