### ISSUE TITLE
Include zip file support

### ISSUE THREAD

**Issue by clsource** [avivbeeri/dome#56]
Currently the engine supports tar files in the form of *.egg files.
I believe the engine could mimic the behaviour of love2d.

you just zip the file in a folder named  `game` and put a file named `main.wren`.
then rename the file `mygame.zip` to `mygame.egg`.

```
mygame.egg
  game/
    main.wren
    other_files....
```

zip files are easier to work with than tar files, because the main operating systems have native support for it without using the command line or downloading special programs.

here is a simple zip lib. https://github.com/kuba--/zip

:)

**Comment by avivbeeri** [comment]
I appreciate the suggestion. I'll have to review this in the roadmap. I'd like to get DOME closer to how Love2D does it's single-file distribution (including what they call "Fused Mode").

The choice between TAR and ZIP has certain drawbacks and advantages, so it isn't completely settled, but integrating a single library to handle TAR was _much_ easier at the time.

I don't expect most people to be using the Egg method for distribution, so if I change it, I won't be considering it a breaking change (or DOME could potentially handle both formats).
