### ISSUE TITLE
Unable to run main.wren with OSX binary

### ISSUE THREAD

**Issue by DeceiptApp** [avivbeeri/dome#65]
Not sure if I'm just doing this incorrectly or what.

When I download the latest OSX binary release .zip, unzip it and put the dome executable in the same root level directory as the main.wren file of my game, I get the following terminal message. I'm assuming that I get this because it can't find my main.wren file for some reason? Help would  be greatly appreciated. 

```
Last login: Sun May  3 19:09:10 on ttys001
/Users/skelteon/Desktop/COB_OSX/dome-1.1.1-macosx-x64/dome ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Dres-MacBook-Pro:~ skelteon$ /Users/skelteon/Desktop/COB_OSX/dome-1.1.1-macosx-x64/dome ; exit;
Error: Could not find a default entry path.


Usage: 
  dome [-d | --debug] [-r<gif> | --record=<gif>] [-b<buf> | --buffer=<buf>] [entry path]
  dome -h | --help
  dome -v | --version

Options: 
  -b --buffer=<buf>   Set the audio buffer size (default: 11)
  -d --debug          Enables debug mode
  -h --help           Show this screen.
  -v --version        Show version.
  -r --record=<gif>   Record video to <gif>.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by DeceiptApp** [comment]
Edit: I was placing the binary in the same directory as the game files and then doubleclicking the binary. I tried running ./dome in terminal from that directory and it worked. Is there any way to run the game by clicking a file, rather than running it from terminal?

**Comment by DeceiptApp** [comment]
Figured this out using [Platypus](https://sveinbjorn.org/platypus) to create a .app from a bash script that simply runs `./dome`.

**Comment by avivbeeri** [comment]
Hi there, 

This is a known issue. For some reason, Finder on macOS doesn't use the correct "current working directory", which prevents DOME finding the correct file. I intend to do some further research into fixing this, but it's low priority due to the solution you came across. 

I do most of my development with DOME in a terminal, so it doesn't often come up for me.
