### ISSUE TITLE
Add iget() or ImageData.pget() function

### ISSUE THREAD

**Issue by doczi-dominik** [avivbeeri/dome#70]
Hi! I really like this project so far. :)

I think it would be useful to get colors from images, not just from the canvas. Since you seem to be inspired by PICO-8, think of it as the `sget()` function from the PICO-8 API. This would be useful to for example store a collision map of a game with white for solid objects, black/transparent for background elements.

Drawing to the canvas using `ImageData.drawArea` then using `Canvas.pget` works fine enough, but I thought this would make a great little addition to the DOME API. :)

**Comment by avivbeeri** [comment]
Hey there, thank you for your kind words.

I agree with you, it would be useful. I was actually considering this quite recently, so I wouldn't be surprised for it to show up on the roadmap sooner than later.

It would likely be `ImageData.pget` and `ImageData.pset`, to match the Canvas API. (I actually see a lot of general overlap between ImageData and Canvas, fundamentally, so I would expect a lot of crossover in the future.)

**Comment by doczi-dominik** [comment]
Thank you so much for the quick response! I'm very glad that you agree, looking forward to future updates!
