### ISSUE TITLE
Add separate input checking for pressed / held down button. 

### ISSUE THREAD

**Issue by doczi-dominik** [avivbeeri/dome#71]
Having separate built-in functions like `isKeyDown` and `isKeyPressed` for keyboard, mouse button and gamepad would go a long way for helping developers create menus or other UI elements where holding down a button simply does not work.

---

An example "terminology" would be:

`isKeyDown(keycode)`: Serves the same purpose as the current implementation. Checks for continuous input, useful for movement, etc.

`isKeyPressed(keycode, [delay])`:  Checks if the key is down now, but was not down the previous frame. Another function with a second parameter could implement key repeat with the provided delay. Useful for navigating menus, textboxes, etc.

#### Would love to hear your thoughts on this!

**Comment by avivbeeri** [comment]
This is actually the very next thing on the roadmap, although I haven't decided how I want to implement it yet.

**Comment by immersivegamer** [comment]
If someone needs a in script way of doing this you can try this code out I'm using. Is a way to keep track of the state of keys to know if it was pressed or released that frame. If I have time I can write more to figure out a key pressed repeat.

https://gist.github.com/immersivegamer/e5b0b7edc6a24685c1e13ff73d3103eb

**Comment by avivbeeri** [comment]
I've been using a library to handle this stuff, including key-repeating for menus, but the fact I've used it in every project is part of why I want to move some of the functionality into the main engine.

It's not a simple API to design, and it requires a couple architectural changes to accommodate.
