### ISSUE TITLE
Add an option to fully rotate a drawable

### ISSUE THREAD

**Issue by itstimeforthe** [avivbeeri/dome#73]
In ImageData transform for "angle" instead of making it round to 90 degrees, have the image just rotate to whatever degree you put in angle. Or if that can't be done for reasons maybe make another method in Drawable to allow for rotation.
Or not I don't know how difficult it would be to put in, do what you want.

**Comment by avivbeeri** [comment]
Hey, Thank you for your interest in DOME!

I've tried a few approaches at this in the past for getting rotation to work correctly (see #39 and #40 ), but I wasn't happy with them at the time. Rotation of small resolution sprites doesn't look particularly appealing, so I didn't see too much benefit investing more time into it than I had.

My main use-case for DOME is a fairly small canvas and small sprites (usually 8x8 or 16x16, rarely 32x32 or larger), and at these sizes, it's better to hand draw rotation sprites for a quarter turn, and then use DOME's angle setting.

I'll add it to my roadmap for the future, if the feature is in high demand.
