### ISSUE TITLE
[idea] Support command line params in Wren

### ISSUE THREAD

**Issue by clsource** [avivbeeri/dome#87]
Dome could provide some API to access command line params.
So games can change their behaviours depending on these params.

Some quick draft

```js

import "dome" for Args
class Game {
    static init() {
           Args.dome // A Map that stores the argv with DOME specific params (like --debug)
          Args.app // A Map that stores the argv with all the other Not standard DOME params
         Args.all // Args.dome + Args.app params
    }
}
```

**Comment by avivbeeri** [comment]
In general, the order of arguments is significant in command line tools, so
an array-style of access may be better.

**Comment by clsource** [comment]
One thing that I would like to know if this lib should be on its own namespaces like

```js
import "args" for Args
```

or its best to add to an available module like `dome`.

Its clearly that this module would need access to the C backend the same as the `Version` class.

**Comment by avivbeeri** [comment]
Args processing should be considered part of the dome.Process class, as
it's a property of the running process.
