### ISSUE TITLE
2D drawing - Thicker lines

### ISSUE THREAD

**Issue by PureFox48** [avivbeeri/dome#92]
This isn't an issue as such but I thought you might be interested to know that I've been using DOME to successfully create some fancy 2D static images. Basically, I just do all the drawing from the init() method or from methods called by it. I leave the update() and draw() methods empty.

It might be worth mentioning in your blurb that this is possible as it may widen the project's appeal.

One thing that would be useful for future versions is to be able to draw lines etc. with a different thickness than one pixel. At present, I just draw the line the required number of times after offsetting the start and end co-ordinates appropriately.

**Comment by avivbeeri** [comment]
Thank you so much for the feedback!

If you have any resources about drawing thicker lines, I can look into it!

**Comment by PureFox48** [comment]
There's an article [here](http://kt8216.unixcab.org/murphy/index.html)  - basically a modification to Bresenham's line drawing algorithm - which might help you decide whether this would be worth doing.

**Comment by avivbeeri** [comment]
I've drafted a prototype implementation to achieve this effect in what I hope is a more efficient, if less accurate manner.
![screenshot](https://user-images.githubusercontent.com/1446063/95575832-54f0c680-0a27-11eb-95bf-a1d59e8c4cc3.png)

**Comment by PureFox48** [comment]
Wow, those look great :)

Hope a thickness option will be added in due course. Perhaps an overload of Canvas.line with an extra parameter.

**Comment by avivbeeri** [comment]
That's how it's currently implemented, API wise.

I'm trying to decide the best way to generate the line cross-section at the moment.
